In [1]:
import numpy as np

In [2]:
big_array = np.arange(10000).reshape(100, 100)
print(big_array)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [3]:
less_than_100 = big_array[big_array < 100]
print(less_than_100)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
less_equal_than_10 = big_array[big_array <= 10]
print(less_equal_than_10)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [10]:
between_10_and_100 = big_array[(big_array > 10) & (big_array < 100)]
print(between_10_and_100)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82
 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [14]:
big_array[(big_array > 10) & (big_array < 9999)] = 0 # update big_array
print(big_array)

[[   0    1    2 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0 9999]]


In [15]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

In [17]:
print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.setdiff1d(y, x))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[6 7 8]
[1 2 3 4 5 6 7 8]


# Sorting

When used as a _function_, sort happens out of place, meaning we have to assign the value to something else to get the sorted array. When used as a _method_, the array gets sorted in place, so it is changed.

In [18]:
x = np.random.randint(1, 11, size=(10,))
print(x)

[8 2 7 9 3 2 9 3 6 1]


In [19]:
print(np.sort(x))
print(x)

[1 2 2 3 3 6 7 8 9 9]
[8 2 7 9 3 2 9 3 6 1]


In [20]:
print(x.sort()) # as a method, sort does not return anything, since the sort is done in place
print(x)

None
[1 2 2 3 3 6 7 8 9 9]


Sorting rank-two arrays can be done by rows or columns:

In [22]:
y = np.random.randint(1, 11, size=(5, 5))
print(y)

[[ 6  3  5  2  9]
 [ 2  5  2 10  6]
 [ 1  3  3  2  4]
 [ 6  3  5  9  9]
 [ 9  8  8  6  2]]


In [23]:
print(np.sort(y, axis=0))

[[ 1  3  2  2  2]
 [ 2  3  3  2  4]
 [ 6  3  5  6  6]
 [ 6  5  5  9  9]
 [ 9  8  8 10  9]]


In [24]:
print(np.sort(y, axis=1))

[[ 2  3  5  6  9]
 [ 2  2  5  6 10]
 [ 1  2  3  3  4]
 [ 3  5  6  9  9]
 [ 2  6  8  8  9]]
